spring:
    application:
        name: VendorManagement
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5455/vendor
        username: postgres
        password: postgres
    jackson:
        default-property-inclusion: non_null